language: scala

jdk: oraclejdk8

scala:
  - 2.12.0

services:
  - docker

before_script:
  - cd $TRAVIS_BUILD_DIR/scripts
  - chmod 777 sbt.sh influxdb.sh
  - ./sbt.sh
  - ./influxdb.sh

script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport coveralls