language: scala
sudo: required
jdk:
- openjdk8
scala:
- 2.11.12
- 2.12.8
- 2.13.1
services:
- docker
script: "./scripts/test.sh"
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.m2"
ignore:
- changelog/*
- scripts/*
- benchmark/*
- examples/*
- docs/*
before_install:
- |
  if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_aaa7ed714ca2_key -iv $encrypted_aaa7ed714ca2_iv -in secrets.tar.enc -out secrets.tar -d
    tar xvf secrets.tar
  fi
jobs:
  include:
  - stage: release
    script: chmod 777 scripts/release.sh && ./scripts/release.sh
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.13.1
  - stage: publish
    script:
    - chmod 777 scripts/publish.sh
    - ./scripts/publish.sh
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.13.1
stages:
- name: test
- name: publish
  if: branch = master AND type != pull_request
- name: release
  if: branch = master AND type != pull_request
env:
  matrix:
  - INFLUXDB_VERSION=1.4.3
  - INFLUXDB_VERSION=1.5.3
  - INFLUXDB_VERSION=1.6.5
  - INFLUXDB_VERSION=1.7.3