language: scala

jdk: oraclejdk8

scala:
  - 2.12.0

services:
  - docker

before_script:
  - wget -q https://dl.bintray.com/sbt/debian/sbt-0.13.15.deb
  - sudo dpkg -i sbt-0.13.15.deb

script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport coveralls