language: scala

sudo: required

jdk: oraclejdk8

scala:
  - 2.12.0

before_script:
  - unset SBT_OPTS JVM_OPTS
  - chmod 777 $TRAVIS_BUILD_DIR/scripts/sbt.sh $TRAVIS_BUILD_DIR/scripts/influxdb.sh
  - $TRAVIS_BUILD_DIR/scripts/sbt.sh
  - $TRAVIS_BUILD_DIR/scripts/influxdb.sh

script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport coveralls