language: scala

sudo: required

jdk:
  - oraclejdk8

scala:
  - 2.11.8
  - 2.12.8

services:
  - docker

script: ./scripts/test.sh

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"
    - "$HOME/.m2"

ignore:
  - "changelog/*"
  - "scripts/*"
  - "benchmark/*"
  - "examples/*"
  - "docs/*"

before_install:
  - |
    if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_aaa7ed714ca2_key -iv $encrypted_aaa7ed714ca2_iv -in secrets.tar.enc -out secrets.tar -d
      tar xvf secrets.tar
    fi

jobs:
  include:
    - stage: release
      script: chmod 777 scripts/release.sh && ./scripts/release.sh
      env: INFLUXDB_VERSION=1.7.3
      scala: 2.12.8
      # Stages splited by modules to fit into 50 min job limit
      # scala 2.11 stages
      # Deploying core modules
    - stage: publish_core_2.11
      script:
        - chmod 777 scripts/publish/core.sh
        - ./scripts/publish/core.sh $TRAVIS_SCALA_VERSION
      env: INFLUXDB_VERSION=1.7.3
      scala: 2.11.8
      # Deploying ahc modules
    - stage: publish_ahc_2.11
      script:
        - chmod 777 scripts/publish/ahc.sh
        - ./scripts/publish/ahc.sh $TRAVIS_SCALA_VERSION
      env: INFLUXDB_VERSION=1.7.3
      scala: 2.11.8
      # Deploying akka modules
    - stage: publish_akka_2.11
      script:
        - chmod 777 scripts/publish/akka.sh
        - ./scripts/publish/akka.sh $TRAVIS_SCALA_VERSION
      env: INFLUXDB_VERSION=1.7.3
      scala: 2.11.8
      # Deploying url modules
    - stage: publish_url_2.11
      script: ./scripts/publish/url.sh $TRAVIS_SCALA_VERSION
      env: INFLUXDB_VERSION=1.7.3
      scala: 2.11.8
      # Deploying other(udp, macros) modules
    - stage: publish_other_2.11
      script: ./scripts/publish/other.sh $TRAVIS_SCALA_VERSION
      env: INFLUXDB_VERSION=1.7.3
      scala: 2.11.8

      # scala 2.12 stages
    - stage: publish_core_2.12
      script:
        - chmod 777 scripts/publish/core.sh
        - ./scripts/publish/core.sh $TRAVIS_SCALA_VERSION
      env: INFLUXDB_VERSION=1.7.3
      scala: 2.12.8
      # Deploying ahc modules
    - stage: publish_ahc_2.12
      script:
        - chmod 777 scripts/publish/ahc.sh
        - ./scripts/publish/ahc.sh $TRAVIS_SCALA_VERSION
      env: INFLUXDB_VERSION=1.7.3
      scala: 2.12.8
        # Deploying akka modules
    - stage: publish_akka_2.12
      script:
        - chmod 777 scripts/publish/akka.sh
        - ./scripts/publish/akka.sh $TRAVIS_SCALA_VERSION
      env: INFLUXDB_VERSION=1.7.3
      scala: 2.12.8
      # Deploying url modules
    - stage: publish_url_2.12
      script:
        - chmod 777 scripts/publish/url.sh
        - ./scripts/publish/url.sh $TRAVIS_SCALA_VERSION
      env: INFLUXDB_VERSION=1.7.3
      scala: 2.12.8
      # Deploying other(udp, macros) modules
    - stage: publish_other_2.12
      script:
        - chmod 777 scripts/publish/other.sh
        - ./scripts/publish/other.sh $TRAVIS_SCALA_VERSION
      env: INFLUXDB_VERSION=1.7.3
      scala: 2.12.8

stages:
  - name: test
  - name: release
    if: branch = master AND type != pull_request
  # 2.11 stages
  - name: publish_core_2.11
    if: branch = master AND type != pull_request
  - name: publish_ahc_2.11
    if: branch = master AND type != pull_request
  - name: publish_akka_2.11
    if: branch = master AND type != pull_request
  - name: publish_url_2.11
    if: branch = master AND type != pull_request
  - name: publish_other_2.11
    if: branch = master AND type != pull_request
  # 2.12 stages
  - name: publish_core_2.12
    if: branch = master AND type != pull_request
  - name: publish_ahc_2.12
    if: branch = master AND type != pull_request
  - name: publish_akka_2.12
    if: branch = master AND type != pull_request
  - name: publish_url_2.12
    if: branch = master AND type != pull_request
  - name: publish_other_2.12
    if: branch = master AND type != pull_request

env:
  matrix:
    - INFLUXDB_VERSION=1.4.3
    - INFLUXDB_VERSION=1.5.3
    - INFLUXDB_VERSION=1.6.5
    - INFLUXDB_VERSION=1.7.3
  global:
    - secure: eQb2hjfBI8JTWgKgk7SQSY/ap7ZAOeHKxcmFT08sGuu85rnEHf5OCSpZdCmbmB4Ct5mt8k2rhULGw8z5XWtmE8aoXZ0jPEl9ny9EMN0chSaBpmrr0lEJqIO7Hy/IpfvHKU48+bxh/+D/zO2jWKfzh1x+oDZES6e6SCqo5b6lrA3X0k1foJE/PzBXIa06Zntzyq2B8zfdmgSNKf76ByV1K3kAF6ohVM3bNnCFw9AsGBSfHQ/RCNNarlzZO8ZIpadHayY/Xl6faTtKwGSByfDoo67gbFFkE3FLb3Wh0aj1cyJ4eeI5VQL0D4Rrf6hMjX3X1tHe7brFpgZp9qciEY/MAD43RqYjXTnl8GNrYRqG0ytEEP/udN/b9CKd5/m9cmvxL2U1S1qwu+OXl6h8ICcfwiGijb4pkOG88b2SuUSQLx0luCJ6PuOl5ExEwiTjwuTJQnhkYfAMZu1SEowfCnFDynsVDPDs6/uXoQvm/CXsCtc38qH8xFEpli8XA5R6ihQgFljK7D5oAyyVFQk+RbH/lyzHTnmjSucvsAziNvFXpV0bPO0Mv2Imn+EoDrvnEUKFlz3YxUfVcCx+TgFkDIuJnJhTU5Uou/OOQrq6Zc5AiyAflMJ5k9EqcU1l2SdzN2tvyrHAZabrMELtS9b2qP6XynefSBoAlFecbmO76rpfmZo=
    - secure: pQlGxYBXQdwTuQm5wjcScUCT2UhPH1iR4axze+C8tGN8Loz2BXkTRkEo4zAz4OpLfqI4iET+G8wQVtxhUzuWBsSBryAID5ZeLvJ6gzWk/jJWGehqUE5v+cvCbgxzrkW11VUigTj7Yd9g0VJPilYHT2sqv16ZLzhn+v+v+lS0goTeKxeokfJN3v23HFdJbffUxrRpETi2HPhNG8M/62+0Gmiap90LaCaUGUS4F7HwKJ1ZHOHthi9naQd/rPv9c3y+aWuSqlar7XuhhagTcuXZ5dbc3LukdHjOOWDTclzKgcp9qYSWo9+hLp81cW9Sg4hsA9gvzZiWQmOrVsszlSLRg7ryv1E7CIXst6mLuhqtjBFoKWE0qCwpZWNTVrYX/quPUMFSUQWMAp0nIsWeP+6x75iZwS8OLixnOh/k55JK1zhOIYcascb3N6iU8zEWA4j2tkY8rjvXcTUu5VkCZkIZ3uRxmbLq6KZvdxjQj5TkVWbEnUmk7k1ZnSuiyzOC07xI6M/Cn39uMamfzgc+nw19/+kPiCyHr20pk4cbwS1r+ToH4+9hc0Dp12Qv2Uj2zMM0jL+V+HhWRr5J1qDlHT/MWO7dOLHK5Qhno6ES8/QNFBaoYwgWUg1UMrkupxqailNoT4DYpG8b9CmNTmjTe3xVOfyJJo6vYpqGpUfilgEWsT0=
    - secure: tCOynwiQmE/u9/qfAh9L6TgFmIwSlTERpZ8eqcEY4BXDarjzn8tVoYtMT4o/YRggF0sZ3UbhzM7okxyEvkFgX1DQ3t4b1KwambChPwX5HxlanHBBmRp0KqUWdMHrkacOYZwNKKZ1j7p07ZNvXssVdWq3Iuk/rYv0EFNOkiKuMzQe2FbuIPz4o+9fikHlNDSVFnl4zM9fwSqI3kXD0DOSzQzTPSQ/X09hhHWdK1rTUhdrRoMHGr0L7bzgmot3bNIfB9pkOOyh0CKcCg+Q57FOtYLfiTijwCQAfXi+f8MawwB9qwFMQlk1Jivs5Q9+St4AaE9InYxW17H2hIK9mZgGv3HysAzYqVRH1TkkRCZUKzAjYW8qnPkOEWyeeXBQbkYRrdBy3+p+Sx4crvtWogsnSJ2yBgQpFMJGLY+zO9ihTD3DF35DH+mO1Dn3DNpf9ltJk99foj6+JlIbuPWfrcA/NMjFx3WUGN5kYcP/XcVLvvRnQgUdHt0GrA6nMl6+mJ/IIOurQGKvbfOSbS1aH6HlOrfymM4r6niwvmRVT2Zl1Ybj/OL16le+8YYVmyugfMbmgTs3aooeZD8SE5USsC/P96zRJrk0cWdArKBrOlzJm1pZEYOk7HkDv7d9o9TsZ3sX0C9PTNfEWjTN61hqXDvWRGoCb9t3HJN+qxiCzRaW3Is=
    - secure: JpFgbZI+lL64imJYnfFFCog/aETawhRzcxa1D+y8NmCHiI2yX+4jIvZA41yC3mA03qKNyhzCrfJmOiv6Z6C0DdR8pEEdshYYtOCg644rrko9w9g4581cRgeN5pQJaE2zkV8CpguEfPf27sW0TEIL1Ievwvdi4JRUVEoicpvcFOO2txf9/s9Y5NzVRUndFWnZevQUBFmJLudjF7qPM5/L7E1e5cSiySG+qqxTd5qlzd9b2BOR3Qxa4b8d3RGkmRE6T68cTi/IGUjcesIkhdCkGS/EcTe1oGIMR/bhy4UtsD6R98B7wpft62sFiibNAA0Oww66yT2fiEnOsXvXrbMW7ra4CqQWrpI5T1X0OaSO1FBNP9C3zefKJRXRJB5W6eu1E7be85qF676mNJlksagMJLBKerv59LQGIqeK55F1Jp/HQBdvRn/2Gvo0o0sz8aOTqeVPUDD6W2pNzOLNBxou0RvCjS0nY/tINkyPsksLFQUJahilsEymUaQJZLh7Fq4976NzAowPO01at1KjEyD9hDNabii3H/17L7E4uDmjc598QtRw02iPNA/U5T5VQr3OkvsplYJZ6645VTWhSnIN0MuloSrYTjqUWpDm5lIO1YGKmlbqbh9DzXdGb/MdORCZi6sXpRaxd5vb3+Pjz4J7e0Iqd4jHOZ8fhH0S51rKtMw=
    - secure: c9EG++jsv2Y47UmnbmzKhORM5gKgybVVi+3M4C63/JTkwB2uoj67sohNkgCENMZl7v2gYtXCIvNznjHivFF2xmFCAuAOLjEi57LgyC3++k6v2+y5T5KV5WIzIECqHtAUmGDNfMsYTiQJgo+7nxTTqJsSimBMFjMjAn/HgHD1zok6OnAUTiprwd193cczn7Wc6VFh5D18NGSFWyfCS8D4zRl0aHL/SskLFyxngZR+uPuZALELzFwNjYcerEDjL/aRnvIkbb9hDtgH8M6+v7KqvEP2pYEZNEXOhRF7G+vQk/boFy7hkaHiNxURPvIWuQu09mFiArxSf+6QbYrxVRFWOEWdLaMf4FiHIz1bpVzupsqWTCBBa5kXNBvaDaCEIRE10xnvgVzP6DFtD9hWjiMwV3oppP8BFKjy5YJ84FnuJeAMkJ1HNVBPztfZAyCLDc5kj4oD0bwbpPGC2DEFH2NtNk5ER3ApluYRqR6xLFMsLCrbWYdhw5rbSwQR04WCp2t+PVHFb1o0mC2w1SnIN0C5btfw2N4y9NVkelXWbvKzXLbB1Xlg8ufJTb7ljP2fB7A0Yp5du62I8XusS1Va2yYK881XKX3kNhblpvPs9NgN7ZdkMatC6BLReTWBvOZuFywHbRIp5L330b763mjY2p3z3nXCv0ZqJjVh6H4N27AXTqA=
    - secure: IQ0NlWEo69DkUIldWKyn4jCJuvb2cKS0VLetL7Vw6gTI65CufEZ9OWXlghbUz0EADI5f5PGXAjqt/qMoBfLtGtcNrtFnoiXQdEgIwsVa/gaR4WcBG+//XqwdHWy1DqG8r+N+KAnlHvpMGwXVHzlEB06R1QGlOW9mG66a3AMFVZ7rFzwZQtSX1RwzsMoO5pzt0jzA3zCjpgRQsekcmZT/zs2jZ0IYhM+SR/w5+Ko94rgAuH8NC04NcsrmcxM+P4Zsz2JmDvCBtDOhhtlDO+2hSpjAXEByPcr1AX+5GYDRyedlvcVgU3DoVKWDxJ7etsveDUbuvEsCs2tojFPmqKkkAPXhPWVw3sO+/luQ5n8AopXHFTQmxOaiMfnKKcEp+Z1bFqAWCCa8yO2CknmeJMdnAjrRivKEIprqeHqBEQfSpeCRAjLSTcKWs/n5ulqdM41SUjkvLKmUMbJ3lfx3Yc9fDNngNyPprzp1JmowswVDhTVAswtGji3XK0xI1VdJ95CaQzOMFC98Jy2jmY9B9i13Vg5v+rQIGtAR9ChsJI1TDLfBG5VQwmpgch6Uaj79lPRKY1izN2wYhSjowBjsHmPq9Tf2mpAVCOXVVuilcip34VOWYclrQDsuNJ7ECkw6gy+pYAMhRplVtJtpzONLltQNYYgjrntBF3SczpIOISKmkek=
