language: scala

jdk: oraclejdk8

scala:
  - 2.12.0

services:
  - docker

before_script:
  - chmod 777 ~/scripts/sbt.sh ~/scripts/influxdb.sh
  - ~/scripts/sbt.sh
  - ~/scripts/influxdb.sh

script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport coveralls