language: scala
sudo: required
jdk:
- openjdk8
scala:
- 2.11.12
- 2.12.8
- 2.13.1
services:
- docker
script: "./scripts/test.sh"
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.m2"
ignore:
- changelog/*
- scripts/*
- benchmark/*
- examples/*
- docs/*
before_install:
- |
  if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_aaa7ed714ca2_key -iv $encrypted_aaa7ed714ca2_iv -in secrets.tar.enc -out secrets.tar -d
    tar xvf secrets.tar
  fi
jobs:
  include:
  - stage: release
    script: chmod 777 scripts/release.sh && ./scripts/release.sh
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.12.8
  - stage: publish_core_2.11
    script:
    - chmod 777 scripts/publish/core.sh
    - "./scripts/publish/core.sh $TRAVIS_SCALA_VERSION"
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.11.8
  - stage: publish_ahc_2.11
    script:
    - chmod 777 scripts/publish/ahc.sh
    - "./scripts/publish/ahc.sh $TRAVIS_SCALA_VERSION"
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.11.8
  - stage: publish_akka_2.11
    script:
    - chmod 777 scripts/publish/akka.sh
    - "./scripts/publish/akka.sh $TRAVIS_SCALA_VERSION"
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.11.8
  - stage: publish_url_2.11
    script: "./scripts/publish/url.sh $TRAVIS_SCALA_VERSION"
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.11.8
  - stage: publish_other_2.11
    script: "./scripts/publish/other.sh $TRAVIS_SCALA_VERSION"
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.11.8
  - stage: publish_core_2.12
    script:
    - chmod 777 scripts/publish/core.sh
    - "./scripts/publish/core.sh $TRAVIS_SCALA_VERSION"
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.12.8
  - stage: publish_ahc_2.12
    script:
    - chmod 777 scripts/publish/ahc.sh
    - "./scripts/publish/ahc.sh $TRAVIS_SCALA_VERSION"
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.12.8
  - stage: publish_akka_2.12
    script:
    - chmod 777 scripts/publish/akka.sh
    - "./scripts/publish/akka.sh $TRAVIS_SCALA_VERSION"
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.12.8
  - stage: publish_url_2.12
    script:
    - chmod 777 scripts/publish/url.sh
    - "./scripts/publish/url.sh $TRAVIS_SCALA_VERSION"
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.12.8
  - stage: publish_other_2.12
    script:
    - chmod 777 scripts/publish/other.sh
    - "./scripts/publish/other.sh $TRAVIS_SCALA_VERSION"
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.12.8
  - stage: publish_core_2.13
    script:
    - chmod 777 scripts/publish/core.sh
    - "./scripts/publish/core.sh $TRAVIS_SCALA_VERSION"
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.13.0
  - stage: publish_ahc_2.13
    script:
    - chmod 777 scripts/publish/ahc.sh
    - "./scripts/publish/ahc.sh $TRAVIS_SCALA_VERSION"
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.13.0
  - stage: publish_akka_2.13
    script:
    - chmod 777 scripts/publish/akka.sh
    - "./scripts/publish/akka.sh $TRAVIS_SCALA_VERSION"
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.13.0
  - stage: publish_url_2.13
    script:
    - chmod 777 scripts/publish/url.sh
    - "./scripts/publish/url.sh $TRAVIS_SCALA_VERSION"
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.13.0
  - stage: publish_other_2.13
    script:
    - chmod 777 scripts/publish/other.sh
    - "./scripts/publish/other.sh $TRAVIS_SCALA_VERSION"
    env: INFLUXDB_VERSION=1.7.3
    scala: 2.13.0
stages:
- name: test
- name: release
  if: branch = master AND type != pull_request
- name: publish_core_2.11
  if: branch = master AND type != pull_request
- name: publish_ahc_2.11
  if: branch = master AND type != pull_request
- name: publish_akka_2.11
  if: branch = master AND type != pull_request
- name: publish_url_2.11
  if: branch = master AND type != pull_request
- name: publish_other_2.11
  if: branch = master AND type != pull_request
- name: publish_core_2.12
  if: branch = master AND type != pull_request
- name: publish_ahc_2.12
  if: branch = master AND type != pull_request
- name: publish_akka_2.12
  if: branch = master AND type != pull_request
- name: publish_url_2.12
  if: branch = master AND type != pull_request
- name: publish_other_2.12
  if: branch = master AND type != pull_request
- name: publish_core_2.13
  if: branch = master AND type != pull_request
- name: publish_ahc_2.13
  if: branch = master AND type != pull_request
- name: publish_akka_2.13
  if: branch = master AND type != pull_request
- name: publish_url_2.13
  if: branch = master AND type != pull_request
- name: publish_other_2.13
  if: branch = master AND type != pull_request
env:
  matrix:
  - INFLUXDB_VERSION=1.4.3
  - INFLUXDB_VERSION=1.5.3
  - INFLUXDB_VERSION=1.6.5
  - INFLUXDB_VERSION=1.7.3