version: 2
jobs:
  build:
       docker:
         - image: circleci/openjdk:8-jdk
       steps:
         - checkout
         - run:
             name: Insatll sbt
             command: |
                wget -q https://dl.bintray.com/sbt/debian/sbt-1.1.0.deb
                sudo dpkg -i sbt-1.1.0.deb
  akkaHttp:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run:
            name: Test
            command: "sbt + \"project akkaHttp\" fullTest"
  asyncHttp:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run:
            name: Test
            command: "sbt + \"project asyncHttp\" fullTest"
  udp:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run:
            name: Test
            command: "sbt + \"project udp\" fullTest"
  core:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run:
            name: Test
            command: "sbt + \"project core\" fullTest"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - akkaHttp:
          requires:
            - build
      - asyncHttp:
          requires:
            - build
      - udp:
          requires:
            - build
      - core:
          requires:
            - build