version: 2
jobs:
  build:
       docker:
         - image: circleci/openjdk:8-jdk
       steps:
         - checkout
         - run:
             name: Insatll sbt
             command: |
                echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
                sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
                sudo apt-get update
                sudo apt-get install sbt
  test:
      docker:
        - image: circleci/openjdk:8-jdk
        - image: influxdb:1.3.9
      steps:
        - checkout
        - run:
            name: Compile sources
            command: sbt compile
        - run:
            name: Compile test sources
            command: sbt test:compile
        - run:
            name: Run coverage
            command: sbt coverage
        - run:
            name: Run tests
            command: sbt test
        - run:
            name: Run coveralls
            command: sbt coverageReport coveralls
workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build