version: 2
jobs:
  build:
       docker:
         - image: circleci/openjdk:8-jdk
       steps:
         - checkout
         - run:
             name: Insatll sbt
             command: |
                - wget -q https://dl.bintray.com/sbt/debian/sbt-1.1.0.deb
                - sudo dpkg -i sbt-1.1.0.deb
  test:
      docker:
        - image: circleci/openjdk:8-jdk
        - image: influxdb:1.3.9
      steps:
        - checkout
        - run:
            name: Compile sources
            command: sbt compile
        - run:
            name: Compile test sources
            command: sbt test:compile
        - run:
            name: Run coverage
            command: sbt coverage
        - run:
            name: Run tests
            command: sbt test
        - run:
            name: Run coveralls
            command: sbt coverageReport coveralls
workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build